# Generated by Django 2.1.4 on 2019-04-17 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adname', models.CharField(max_length=50, verbose_name='广告名称')),
                ('adimage', models.ImageField(upload_to='advert/%Y/%m', verbose_name='侧边广告图')),
                ('adurl', models.URLField(verbose_name='访问地址')),
                ('adindex', models.IntegerField(default=100, verbose_name='顺序')),
                ('ad_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '侧边广告',
                'verbose_name_plural': '侧边广告',
            },
        ),
    ]
