# Generated by Django 2.1.4 on 2019-04-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('user', '0002_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='adtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.TypeInfo', verbose_name='广告类别'),
            preserve_default=False,
        ),
    ]
